[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://userbird.co/*"
  to = "https://app.userbird.co/:splat"
  status = 301
  force = true

[template.environment]
  SENDGRID_API_KEY = "Your SendGrid API key"

[[redirects]]
  from = "/functions/v1/*"
  to = "https://ruqbgoazhyfxrsxbttfp.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer your-token-here"}

[[redirects]]
  from = "/functions/v1/feedback-images*"
  to = "/.netlify/functions/supabase-proxy"
  status = 200
  force = true

[[headers]]
  for = "/widget.js"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200