[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Edge functions configuration
[[edge_functions]]
  path = "/api/generate-reply"
  function = "generate-reply"

# Scheduled function to clean up old documents
[functions.cleanup-old-documents]
  schedule = "@weekly" # Run once per week (or @daily for daily cleanup)

[[redirects]]
  from = "https://userbird.co/*"
  to = "https://app.userbird.co/:splat"
  status = 301
  force = true

[template.environment]
  SENDGRID_API_KEY = "Your SendGrid API key"

# More specific rule FIRST - Route to secure proxy function
[[redirects]]
  from = "/functions/v1/feedback-images*"
  to = "/.netlify/functions/supabase-proxy"
  status = 200
  force = true

# More general rule SECOND
[[redirects]]
  from = "/functions/v1/*"
  to = "https://tapssagpmxnjvdwyafsq.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer your-token-here"}

[[headers]]
  for = "/widget.js"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200